ci: have pre-push checks include full coverage checks instead of just tests

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -1,26 +1,36 @@
 #!/bin/bash
 
-read -p "Tests will run before you push changes remotely, continue ? (y/n): " choice
+read -p "Would you like to run tests and lint checks before you push remotely ? (y/n): " choice
 if [ "$choice" != "y" ]; then
     echo "pre-push hook will not be installed"
     exit 0
 else
-cat <<EOF >> .git/hooks/pre-push
+    cat <<EOF >> .git/hooks/pre-push
 #!/bin/bash
+set -e
 
 echo "Before pushing, did you tie your shoes right ?"
 echo "Running tests.."
-pytest tests --no-header --no-summary -q
+
+./scripts/coverage
 
 if [ \$? -ne 0 ]; then
-  echo "Testing failed. Push aborted."
-  exit 1
-else
-  printf "Testing went successful!\nPushing changes.."
+    echo "hook failed. Push aborted."
+    exit 1
 fi
 
+echo "Running linter.."
+./scripts/lint
+
+if [ \$? -ne 0 ]; then
+    echo -e "\e[1;31mpre-push checks failed!\e[0m\n"
+    exit 1
+else
+    echo -e "\e[1;32mpre-push checks went successful!\e[0m\n"
+fi
 exit 0
+
 EOF
-chmod +x .git/hooks/pre-push
-printf "\e[33mpre-push hook installed!\nTests will run before you push changes\e[0m\n"
+    chmod +x .git/hooks/pre-push
+    printf "\e[33mpre-push hook installed![0m\n"
 fi
